// Code generated by 'yaegi extract gitlab.com/rarify-protocol/templates/yamltpl'. DO NOT EDIT.

package internal

import (
	"gitlab.com/rarify-protocol/templates/yamltpl"
	"reflect"
)

func init() {
	Symbols["gitlab.com/rarify-protocol/templates/yamltpl/yamltpl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Files": reflect.ValueOf(&yamltpl.Files).Elem(),
	}
}
